### ISSUE TITLE
Cannot relocate fsevents binary

### ISSUE THREAD

**Issue by timfish** [zeit/webpack-asset-relocator-loader#2] opened 2019-02-26 15:54 UTC
## Platform: macOS

`package.json`
```
{
  "name": "ncc-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "chokidar": "^2.1.2"
  }
}
```

`index.js`
```
const chokidar = require("chokidar");

chokidar.watch(".", {}).on("all", (event, path) => {
  console.log(event, path);
});
```

```
ncc build index.js
```

Error:
```
Tims-MacBook:ncc-test timfish$ ncc build index.js 
ncc: Module directory "/Users/timfish/Documents/Repositories/ncc-test/node_modules/fsevents/node_modules/node-pre-gyp/lib" attempted to require "aws-sdk" but could not be resolved, assuming external.
ncc: Module directory "/Users/timfish/Documents/Repositories/ncc-test/node_modules/fsevents/node_modules/node-pre-gyp/lib" attempted to require "aws-sdk" but could not be resolved, assuming external.
ncc: Module directory "/Users/timfish/Documents/Repositories/ncc-test/node_modules/fsevents/node_modules/node-pre-gyp/lib" attempted to require "aws-sdk" but could not be resolved, assuming external.
ncc: Module directory "/Users/timfish/Documents/Repositories/ncc-test/node_modules/fsevents/node_modules/node-pre-gyp/lib/util" attempted to require "npm" but could not be resolved, assuming external.
ncc: Module directory "/Users/timfish/Documents/Repositories/ncc-test/node_modules/fsevents/node_modules/node-pre-gyp/lib/util" attempted to require "node-gyp" but could not be resolved, assuming external.
ncc: Module directory "/Users/timfish/Documents/Repositories/ncc-test/node_modules/fsevents/node_modules/node-pre-gyp/lib" attempted to require "request" but could not be resolved, assuming external.
   0kB  dist/node-pre-gyp/bin/node-pre-gyp.cmd
   0kB  dist/nw-pre-gyp/package.json
   0kB  dist/node-pre-gyp/lib/util/nw-pre-gyp/package.json
   0kB  dist/node-pre-gyp/contributing.md
   1kB  dist/node-pre-gyp/appveyor.yml
   1kB  dist/node-pre-gyp/LICENSE
   1kB  dist/nw-pre-gyp/index.html
   1kB  dist/node-pre-gyp/lib/util/nw-pre-gyp/index.html
   2kB  dist/node-pre-gyp/package.json
   2kB  dist/package.json
   3kB  dist/node-pre-gyp/bin/node-pre-gyp
  13kB  dist/node-pre-gyp/CHANGELOG.md
  24kB  dist/node-pre-gyp/lib/util/abi_crosswalk.json
  30kB  dist/node-pre-gyp/README.md
1660kB  dist/index.js
1738kB  [10697ms] - ncc 0.15.2
```

Suspect it's due to [this](https://github.com/strongloop/fsevents/blob/v1.2.7/fsevents.js#L14) in the `fsevents` dependency:
```
var path = require('path');
var binary = require('node-pre-gyp');
var Native = require(binary.find(path.join(__dirname, 'package.json')));

```

**Comment by guybedford** [comment] 2019-02-27 14:33
I just tried this case out and it is working completely fine for me.

Are you running in Windows perhaps?

**Comment by guybedford** [comment] 2019-02-27 14:34
Ah I see you say macOS... would be odd if this was a Mac/Linux difference.

Perhaps try reinstalling to ensure the fsevents build is running? And the code definitely works without an ncc build?

**Comment by timfish** [comment] 2019-02-28 13:44
I'll take another look into this today. `chokidar` bundles fine on Linux and Windows because fsevents is a macOS only optional module.

**Comment by timfish** [comment] 2019-02-28 16:16
I've found a cross-platform module that uses `node-pre-gyp` in a similar way and gives the same warnings, although **it is** outputting a working bundle:

`package.json`
```
{
  "name": "ncc-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "bcrypt": "^3.0.4",
  }
}
```

`index.js`
```
const bcrypt = require('bcrypt');

bcrypt.hash('s0/\/\P4$$w0rD', 10, function(err, hash) {
    console.log('Hash:', hash)
});
```

Build output
```
λ ncc build index.js
ncc: Module directory "C:\Users\tim\Documents\Repositories\ncc-test\node_modules\bcrypt\node_modules\node-pre-gyp\lib" attempted to require "aws-sdk" but could not be resolved, assuming external.
ncc: Module directory "C:\Users\tim\Documents\Repositories\ncc-test\node_modules\bcrypt\node_modules\node-pre-gyp\lib" attempted to require "aws-sdk" but could not be resolved, assuming external.
ncc: Module directory "C:\Users\tim\Documents\Repositories\ncc-test\node_modules\bcrypt\node_modules\node-pre-gyp\lib" attempted to require "aws-sdk" but could not be resolved, assuming external.
ncc: Module directory "C:\Users\tim\Documents\Repositories\ncc-test\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util" attempted to require "node-gyp" but could not be resolved, assuming external.
ncc: Module directory "C:\Users\tim\Documents\Repositories\ncc-test\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util" attempted to require "npm" but could not be resolved, assuming external.
ncc: Module directory "C:\Users\tim\Documents\Repositories\ncc-test\node_modules\bcrypt\node_modules\node-pre-gyp\lib" attempted to require "request" but could not be resolved, assuming external.
   0kB  dist\node-pre-gyp/contributing.md
   0kB  dist\node-pre-gyp/lib/util/nw-pre-gyp/package.json
   0kB  dist\nw-pre-gyp/package.json
   0kB  dist\node-pre-gyp/bin/node-pre-gyp.cmd
   1kB  dist\node-pre-gyp/lib/util/nw-pre-gyp/index.html
   1kB  dist\node-pre-gyp/LICENSE
   1kB  dist\node-pre-gyp/appveyor.yml
   1kB  dist\nw-pre-gyp/index.html
   2kB  dist\node-pre-gyp/package.json
   2kB  dist\package.json
   3kB  dist\node-pre-gyp/bin/node-pre-gyp
  13kB  dist\node-pre-gyp/CHANGELOG.md
  24kB  dist\node-pre-gyp/lib/util/abi_crosswalk.json
  32kB  dist\node-pre-gyp/README.md
 162kB  dist\lib/binding/bcrypt_lib.node
 996kB  dist\index.js
1238kB  [2104ms] - ncc 0.15.2
```

**Comment by guybedford** [comment] 2019-03-07 12:54
Yeah this sounds like a Mac-specific issue. Unfortunately I just got rid of my mac, so can't easily debug this now.

Can you share the exact runtime execution error that you get? The original posted in the issue is the build output not the execution output.

**Comment by guybedford** [comment] 2019-03-18 11:53
@timfish just to let you know the latest version of ncc and this loader have just been published with some fixes for MacOS, which may resolve some of the issues here.

**Comment by styfle** [comment] 2019-03-18 13:17
@guybedford Regarding macOS, see #5

**Comment by guybedford** [comment] 2019-05-22 08:12
I just tested this exact replication case with the new ncc beta release and this is building fine for me, including emitting the `fsevents.node` file.

Closing as resolved, but please reopen if I'm missing anything.

I'll be PR'ing the integration test into ncc itself with the next batch of changes.

**Closed by guybedford** 2019-05-22 08:12 UTC

**Comment by guybedford** [comment] 2019-05-22 08:15
Although note that for support of `require('asdf.node')` files, this requires setting the asset relocation loader to run for these files. See the ncc configuration as an example here - https://github.com/zeit/ncc/blob/master/src/index.js#L146.

**Comment by guybedford** [comment] 2019-05-22 09:16
(I also just checked `bcrypt` and can confirm that is working too)
