### ISSUE TITLE
Error on 2.x upgrade

### ISSUE THREAD

**Issue by samcorcos** [zeit/webpack-asset-relocator-loader#3] opened 2019-03-15 20:08 UTC
I upgraded from 0.1.12 to 0.2.3 and I now get the following error:

```
Defining routes from exportPathMap
(node:32998) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readableIdentifier' of null
    at Object.ModuleFilenameHelpers.createFilename (/Users/xxxx/my-website/node_modules/webpack/lib/ModuleFilenameHelpers.js:83:28)
...
```

There were no other changes to the code and the app still works when I revert to 0.1.12. I'm happy to provide a reproducible demo if needed :)

**Comment by Timer** [comment] 2019-03-15 20:11
@samcorcos providing a small reproducible demo would help immensity in fixing this quickly. 😄

**Comment by samcorcos** [comment] 2019-03-16 20:49
@Timer sure thing! Here's a demo: https://github.com/samcorcos/relocator-bug

I'm not sure it's small enough... but it's not a big app (just a boilerplate).

**Comment by styfle** [comment] 2019-03-20 21:38
@guybedford Could this be related to the `firebase-admin` bug https://github.com/zeit/ncc/issues/317

**Comment by samcorcos** [comment] 2019-03-21 20:04
@styfle It could be similar (since both use Firebase), but the app I linked to does not include `firebase-admin`.

**Comment by guybedford** [comment] 2019-03-22 15:38
So the error that is coming up here seems to be an internal Webpack error here - https://github.com/webpack/webpack/blob/master/lib/ModuleFilenameHelpers.js#L83.

Which seems to be caused by the `module` object itself being `null`.

I checked the asset loader and there is no actual error being created in the loader itself, so this sounds to me like a Webpack bug, possibly caused by the source provided from the asset loader, but I'm not sure more than that.

@sokra any suggestions how we might go about debugging this further. The only thing I can think of next is a binary search on the codebase to trace the exact section of code causing the issue, but this would be a lot easier with the webpack bug resolved.

**Comment by guybedford** [comment] 2019-03-29 22:12
@samcorcos note that we test this project against Webpack 5 - perhaps ensure you are using that here.

**Comment by samcorcos** [comment] 2019-04-03 18:47
@guybedford I get a different error when I try to use Webpack 5.x alpha:

```
Defining routes from exportPathMap
Got uncaughtException: TypeError: Cannot read property 'tapAsync' of undefined
    at ExternalModuleFactoryPlugin.apply (/Users/xxxx/code/next-firebase-boilerplate/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:18:39)
    at compiler.hooks.compile.tap.params (/Users/xxxx/code/next-firebase-boilerplate/node_modules/webpack/lib/DllReferencePlugin.js:116:68)
    at SyncHook.eval [as call] (eval at create (/Users/xxxx/code/next-firebase-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/xxxx/code/next-firebase-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/Users/xxxx/code/next-firebase-boilerplate/node_modules/next/node_modules/webpack/lib/Compiler.js:615:23)
    at _err1 (eval at create (/Users/xxxx/code/next-firebase-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
    at Array.compiler.inputFileSystem.readFile (/Users/xxxx/code/next-firebase-boilerplate/node_modules/webpack/lib/DllReferencePlugin.js:77:15)
    at Storage.finished (/Users/xxxx/code/next-firebase-boilerplate/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/xxxx/code/next-firebase-boilerplate/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/xxxx/code/next-firebase-boilerplate/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

Progress?

**Comment by guybedford** [comment] 2019-04-08 13:00
@samcorcos that's a really odd error, in that it seems to be again a Webpack-specific issue at https://github.com/webpack/webpack/blob/next/lib/ExternalModuleFactoryPlugin.js#L18.

I'd suggest doing a good old fashioned reduction on the scenario, stripping back the code and webpack configuration in a binary search fashion towards the simple case. Since we can't easily debug Webpack internals, knowing the application code / configuration change that causes the issue is likely the closest we can get to isolation.

**Comment by guybedford** [comment] 2019-04-18 15:23
@samcorcos did you manage to make any further progress here at all?

**Comment by samcorcos** [comment] 2019-04-18 19:07
@guybedford I haven't had time yet. It's still functional on the old version, so it hasn't been a priority.

**Comment by Timer** [comment] 2019-06-25 15:49
I'm going to close this because we've confirmed on a few occasions this relocator works with Firebase 6 now and Next.js. The issue referenced in https://github.com/zeit/webpack-asset-relocator-loader/issues/3#issuecomment-475038843 is also closed.

@samcorcos let us know if you bump into this again.

**Closed by Timer** 2019-06-25 15:49 UTC
